### PR TITLE
fix forms errors

### LINKED ISSUE #5: No form errors feedback
When I want to add a one-shot or a scheduled dataflow and some fields data contains wrong data, the form popin is closed without display the form errors.

### PR DESCRIPTION
**Pull request by jbcr**
fix #5

### CODE REVIEW

**Comment by jeremycr** [comment]
Please run php-cs-fixer

File: src/Controller/ScheduledDataflowController.php [hunk 1]
```diff
@@ -119,10 +124,13 @@ public function edit(Request $request, int $id): Response
...
-            return $this->redirectToRoute('coderhapsodie.ezdataflow.main');
-        } else {
-            return $this->render('@ezdesign/ezdataflow/parts/schedule_edit.html.twig', ['form' => $form->createView()]);
+            return new JsonResponse(['redirect' => $this->generateUrl('coderhapsodie.ezdataflow.main')]);
         }
+
+        return new JsonResponse(['form' => $this->renderView('@ezdesign/ezdataflow/parts/schedule_form.html.twig', [
+            'form' => $form->createView(),
+            'type_action' => 'edit',
+        ])]);
```
Comment (jeremycr) [inline src/Controller/ScheduledDataflowController.php]: The readability can be improved
```php
        return new JsonResponse([
            'form' => $this->renderView('@ezdesign/ezdataflow/parts/schedule_form.html.twig', [
                'form' => $form->createView(),
                'type_action' => 'edit',
            ]),
        ]);
```

File: src/Controller/ScheduledDataflowController.php [hunk 2]
```diff
@@ -65,9 +65,14 @@ public function create(Request $request): Response
...
             }
+
+            return new JsonResponse(['redirect' => $this->generateUrl('coderhapsodie.ezdataflow.main')]);
         }
 
-        return $this->redirectToRoute('coderhapsodie.ezdataflow.main');
+        return new JsonResponse(['form' => $this->renderView('@ezdesign/ezdataflow/parts/schedule_form.html.twig', [
+            'form' => $form->createView(),
+            'type_action' => 'new',
+        ])]);
```
Comment (jeremycr) [inline src/Controller/ScheduledDataflowController.php]: Readability improvement:
```php
        return new JsonResponse([
            'form' => $this->renderView('@ezdesign/ezdataflow/parts/schedule_form.html.twig', [
                'form' => $form->createView(),
                'type_action' => 'new',
            ])
        ]);
```

**Review by jeremycr — CHANGES_REQUESTED** [review]

**Review by jeremycr — APPROVED** [review]
